data_validation:
  data_file_path: data/raw/usa-housing-dataset/USA Housing Dataset.csv
  required_columns: date, price, bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, sqft_above, sqft_basement, yr_built, yr_renovated, street, city, statezip, country
  non_empty_columns: date, price, bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, sqft_above, sqft_basement, yr_built, yr_renovated, street, city, statezip, country
  numeric_columns: price, bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, sqft_above, sqft_basement, yr_built, yr_renovated
  datetime_columns: date
  strict_positive_columns: sqft_living, sqft_lot, sqft_above, yr_built
  warning_non_positive_columns: price
  expected_constant_values: country=USA

data_transformation:
  input_data_path: data/raw/usa-housing-dataset/USA Housing Dataset.csv
  transformed_data_path: artifacts/processed/usa_housing_transformed.csv
  metadata_path: artifacts/processed/usa_housing_transformed.metadata.json
  target_column: price
  date_column: date
  numeric_columns: bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, sqft_above, sqft_basement, yr_built, yr_renovated
  categorical_columns: city
  drop_columns: street, country, statezip, date
  statezip_column: statezip
  state_column_name: state
  zipcode_column_name: zipcode
  drop_non_positive_target: true

data_training:
  input_data_path: artifacts/processed/usa_housing_transformed.csv
  model_artifact_path: artifacts/models/linear_regression_model.pkl
  metadata_path: artifacts/models/linear_regression_model.metadata.json
  model_name: linear_regression
  target_column: price
  numeric_feature_columns: bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, sqft_above, sqft_basement, yr_built, yr_renovated, sale_year, sale_month, sale_day
  categorical_feature_columns: city, state
  test_size: 0.2
  random_state: 42
